### ISSUE TITLE
Type error during test

### ISSUE THREAD

**Issue by Pegahyaftian** [hasanhuz/SpanEmo#11]
When running test.py file, I got error below:

TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found object

any idea on this?
Thanks!

**Comment by hasanhuz** [comment]
Hi, 
Are you using the same dependencies and requirements as suggested in the ReadMe and requirement files?
Thanks

**Comment by Pegahyaftian** [comment]
Yes, I  did! it is ok during training but not during test

**Comment by hasanhuz** [comment]
It looks to me the model is getting empty tensors, can you check if the data_loader is correctly reading the test data and processing them? Maybe you are providing the wrong path of the test file!

**Comment by Pegahyaftian** [comment]
dataloaders correctly reads the file as the output is:
The number of Test batches:  102

**Comment by hasanhuz** [comment]
I'm not sure why you are getting such an issue as I haven't received it myself, but I suggest that you print a sample of the output with their types, hope this can help you figure out what the problem is.

**Comment by Pegahyaftian** [comment]
I noticed that the problem is due to the test file! I replace the test file with other one and it works!

**Comment by hasanhuz** [comment]
Glad to hear that it worked for you :)
