### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by LunaCelestine** [hasanhuz/SpanEmo#15]
Can you please list which portions of the dataset you are using such el-reg, el-oc, etc. I was not able to fully determine how you collated the dataset based on your README and your paper.

Thanks!

**Comment by hasanhuz** [comment]
Hi there, thank you for your interest in our paper. 

This is the one we used "E-c".

Best,

**Comment by LunaCelestine** [comment]
Thanks so much Hasan, fantastic paper!

Cheers,

LC
