### ISSUE TITLE
a problem of code

### ISSUE THREAD

**Issue by tengwang0318** [hasanhuz/SpanEmo#5]
I just try to run the code, I download the dataset, but I got an error about "TypeError: linear(): argument 'input' (position 1) must be Tensor, not str". I check the code, and I find the two lines code maybe have a mistake.
![image](https://user-images.githubusercontent.com/57594482/139265919-bc37906b-c708-44cc-83b9-30f8ac9bf670.png)
I just change them to 
``` 
output = self.bert(input_ids=input_ids)
return output.last_hidden_state
```
but I still got the same mistake, I don't know why.
Here is my [colab code](https://colab.research.google.com/drive/1gSthRbY4-WsrdxRSxdgoq2ON7h3g1KB1)
I would appreciate it if you could help me again!

**Comment by tdlbj** [comment]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/82598911/216355627-fba253f1-ee65-42ec-8b53-f9da7cffd2de.png">
The current time to open the file name. Why does it exist
